import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { useRef, useState } from 'react';
import DeleteConfirmation from '@/components/DeleteConfirmation';import { adminApi, AdminApiError } from '@/lib/client/admin-api';
const push=jest.fn();jest.mock('next/navigation',()=>({useRouter:()=>({push})}));jest.mock('@/lib/client/admin-api',()=>({adminApi:jest.fn(),AdminApiError:class extends Error{constructor(public status:number,message:string){super(message);}}}));
const mock=adminApi as jest.Mock;const id='11111111-1111-4111-8111-111111111111';
function Harness({kind}:{kind:'categoria'|'personalizacao'}){const lockRef=useRef(false);const [busy,setBusy]=useState(false);return <DeleteConfirmation kind={kind} id={id} name="Doces" lockRef={lockRef} busy={busy} setBusy={setBusy}/>;}
afterEach(()=>{mock.mockReset();push.mockReset();});
test('nome exato, foco, cancelar, 204 e trava síncrona',async()=>{
 let resolve!:(value:unknown)=>void;mock.mockImplementation(()=>new Promise(r=>resolve=r));render(<Harness kind="categoria"/>);const trigger=screen.getByRole('button',{name:'Excluir categoria'});fireEvent.click(trigger);await waitFor(()=>expect(screen.getByLabelText('Nome da categoria')).toHaveFocus());fireEvent.change(screen.getByLabelText('Nome da categoria'),{target:{value:'doces'}});expect(screen.getByRole('button',{name:'Confirmar exclusão'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Cancelar'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Excluir categoria'})).toHaveFocus());fireEvent.click(screen.getByRole('button',{name:'Excluir categoria'}));fireEvent.change(screen.getByLabelText('Nome da categoria'),{target:{value:'Doces'}});const confirm=screen.getByRole('button',{name:'Confirmar exclusão'});fireEvent.click(confirm);fireEvent.click(confirm);expect(mock).toHaveBeenCalledTimes(1);resolve(undefined);await waitFor(()=>expect(push).toHaveBeenCalledWith('/categorias'));
});
test('404 e 409 mostram mensagens específicas sem navegação',async()=>{
 for(const kind of ['categoria','personalizacao'] as const)for(const status of [404,409]){mock.mockRejectedValueOnce(new AdminApiError(status,'upstream'));const view=render(<Harness kind={kind}/>);fireEvent.click(screen.getByRole('button',{name:`Excluir ${kind==='categoria'?'categoria':'personalização'}`}));fireEvent.change(screen.getByLabelText(`Nome da ${kind==='categoria'?'categoria':'personalização'}`),{target:{value:'Doces'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar exclusão'}));const alert=await screen.findByRole('alert');expect(alert).toHaveTextContent(status===404?'não encontrada':kind==='categoria'?'produtos':'em uso');if(kind==='personalizacao'&&status===409)expect(alert).toHaveTextContent('disponibilidade');view.unmount();}expect(push).not.toHaveBeenCalled();
});
